### ISSUE TITLE
Won't parse emoji

### ISSUE THREAD

**Issue by wirehack7** [yihangho/emoji-for-jekyll#10]
Hello,

I placed ```emoji_for_jekyll.rb``` and ```emoji.json``` into ```_plugins```.
In ```_config.yaml``` I added ```emoji: true```. In a post I edited the text and added ```:smile:``` into it. When using ```jekyll build``` then it gets not changed to a img element.
What am I doing wrong?
I am using the latest version of that plugin from here and jekyll is version ```jekyll 3.1.6```.

You can view the page at: https://github.com/wirehack7/capsop.com

**Comment by yihangho** [comment]
Hi @wirehack7,

Sorry it took me a while to respond. Can you please check again? I tested on https://github.com/wirehack7/capsop.com/blob/master/_posts/2015-09-19-irc-driven-botnet.markdown and it seems to be working.

Cheers,
Yihang

**Comment by wirehack7** [comment]
Okay works, another plugin interrupted it. The interrupting plugin was ```jekyll-minifier```.
Thank you!

**Comment by yihangho** [comment]
Cool, good to hear that! I'll investigate why it doesn't work with jekyll-minifier.
