### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by stefania11** [yihangho/emoji-for-jekyll#7]
HI, could you please provide some examples of syntax for integrating the emojis in blog text?

**Comment by yihangho** [comment]
@stefania11, for perhaps 99% of the time, all you need to do is run `gem install emoji_for_jekyll`, and add `emoji_for_jekyll` to the list of gems on `_config.yml`, for example: `gems: [emoji_for_jekyll]`.

**Comment by stefania11** [comment]
I did but I am using github pages for deployment and it's not accepting it
in the config file




Stefania Druga - Founder

+1 415 503 89 44

-----------------------------------------------------------------------------


HacKIDemia: Inspire the kids to imagine a better tomorrow

and give them the tools to build it!



Web <http://www.hackidemia.com/>| Facebook
<https://www.facebook.com/Hackidemia>| Twitter
<https://twitter.com/HacKidemia>| YouTube
<http://www.youtube.com/user/HacKIDemia>| Newsletter <http://bit.ly/ZrvxtF>|

**Comment by yihangho** [comment]
GitHub Pages doesn't support arbitrary plugins. You can either use [jemoji](https://help.github.com/articles/emoji-on-github-pages/) or build your site locally and push the built files to your repo.
