### ISSUE TITLE
Issues with Github?

### ISSUE THREAD

**Issue by adilansari** [yihangho/emoji-for-jekyll#8]
Copied over *rb and json to _plugins. Works locally but not on prod. My site is deployed on github.

**Comment by adilansari** [comment]
Github integration should be a feature instead.

**Comment by yihangho** [comment]
@adilansari This is a [known caveat](http://jekyllrb.com/docs/plugins/) with GitHub pages. You may opt to use [Jemoji](https://help.github.com/articles/emoji-on-github-pages/) instead as it is white-listed by GitHub, or you can build the site on your machine and deploy the built HTML (this is what I did when I was using GitHub pages).
