### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by VikramTiwari** [yihangho/emoji-for-jekyll#9]
```
Deprecation: Collection#each should be called on the #docs array directly.
Called by /Users/Vikram/Documents/code/vikram/blog/_plugins/emoji_for_jekll.rb:23:in `generate'.
```

**Comment by yihangho** [comment]
@VikramTiwari Thanks for bringing this up! This is now fixed in [0.2.2](https://rubygems.org/gems/emoji_for_jekyll/versions/0.2.2). Do try it out and let me know if anything is not working.
